name: build and push images

on:
   push:
      branches: [ main ]

jobs: 

  build:
     name: Build images
     runs-on: ubuntu-latest

     steps:
     - name: Checkout repo
       uses: actions/checkout@v3

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         role-to-assume: arn:aws:iam::409158123672:role/my-github-actions-role
         aws-region: us-east-1

     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1

     - name: Build, tag, and push docker image to Amazon ECR
       env:
         REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         REPOSITORY: app-python
         IMAGE_TAG: latest
       working-directory: ./app
       run: |
         docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
         docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
         aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --task-definition $TASK_NAME --region us-east-1 --force-new-deployment